"""Central configuration loaded from environment (.env)."""
import os

from dotenv import load_dotenv

load_dotenv()


def _env(key: str, default: str = "") -> str:
    return os.environ.get(key, default)


# Semantic Scholar
SEMANTIC_SCHOLAR_API_KEY = _env("SEMANTIC_SCHOLAR_API_KEY")
SEMANTIC_SCHOLAR_BASE = "https://api.semanticscholar.org/graph/v1"
# API rule: 1 request per second.
SEMANTIC_SCHOLAR_MIN_INTERVAL = 1.0

# Master switch for every feature that calls the local LLM (Ollama). Off for
# production servers too weak/slow to run an LLM: ingestion/classification,
# infinite-scroll discovery, and detailed-summary enrichment all fall back to
# DB-only behavior instead of attempting an Ollama call (see ingest/pipeline.py,
# routes/fields.py, routes/admin.py). Run ingestion separately (e.g. on a
# machine that does have Ollama, against the same database) and the server
# will serve what's already there.
LLM_ENABLED = _env("LLM_ENABLED", "true").lower() == "true"

# Ollama
OLLAMA_HOST = _env("OLLAMA_HOST", "http://localhost:11434")
OLLAMA_MODEL = _env("OLLAMA_MODEL", "qwen3.5:9b")
# Context window. Ollama defaults to 4096, which truncates long PDF prompts and
# produces terse summaries; raise it so the full-text prompt fits.
OLLAMA_NUM_CTX = int(_env("OLLAMA_NUM_CTX", "8192"))
# Vision model for captioning extracted figures. Empty = disabled (the dense
# qwen3.5:9b is text-only); set e.g. "gemma4:26b" to turn captioning on.
VISION_MODEL = _env("VISION_MODEL", "")
# Small, fast model for the live discovery feed's quick summaries (e.g.
# "qwen2.5:0.5b" or "qwen2.5:3b"). Empty = use OLLAMA_MODEL directly (no fast
# path). When a fast model is set, its summaries are flagged and later
# re-generated by OLLAMA_MODEL via scripts/upgrade_summaries.py.
OLLAMA_FAST_MODEL = _env("OLLAMA_FAST_MODEL", "")
# Concurrent Ollama requests when summarizing a discovery batch.
DISCOVER_CONCURRENCY = int(_env("DISCOVER_CONCURRENCY", "4"))
# Papers fetched per discovery scroll. Bigger = fewer stalls while scrolling.
DISCOVER_BATCH = int(_env("DISCOVER_BATCH", "12"))

# PDF ingestion: read open-access PDFs to ground richer summaries and pull
# figures. Figures are written under MEDIA_DIR and served at /media/figures/.
#
# ENABLE_PDF_INGEST is the master switch (whether to touch PDFs at all). The two
# sub-toggles below independently control the *expensive* halves — full-text
# grounding and figure scanning — so you can keep one without paying for the
# other. When both are off the PDF isn't even downloaded.
ENABLE_PDF_INGEST = _env("ENABLE_PDF_INGEST", "true").lower() == "true"
# Feed the PDF's full text into the detailed summary. This is what lets the model
# ground its explanation in real methods/results and surface the paper's actual
# equations; off = summarize from the abstract only (faster, shallower).
ENABLE_PDF_FULLTEXT = _env("ENABLE_PDF_FULLTEXT", "true").lower() == "true"
# Scan the PDF for figures (embedded raster images + rendered vector graphics).
ENABLE_FIGURE_EXTRACT = _env("ENABLE_FIGURE_EXTRACT", "true").lower() == "true"
# Most scientific figures (plots, diagrams) are vector graphics, not embedded
# raster images, so raster-only scanning finds almost nothing. When on, vector
# drawing regions are rasterized to PNG so those figures are captured too.
ENABLE_VECTOR_FIGURES = _env("ENABLE_VECTOR_FIGURES", "true").lower() == "true"
MEDIA_DIR = _env("MEDIA_DIR", "./media")
PDF_MAX_BYTES = int(_env("PDF_MAX_BYTES", str(40 * 1024 * 1024)))  # 40 MB cap
PDF_TEXT_CHAR_LIMIT = int(_env("PDF_TEXT_CHAR_LIMIT", "16000"))  # ~4k tokens
MAX_FIGURES_PER_PAPER = int(_env("MAX_FIGURES_PER_PAPER", "4"))
MIN_FIGURE_DIM = int(_env("MIN_FIGURE_DIM", "256"))  # px; drop logos/glyphs
# DPI used to rasterize vector-figure regions to PNG. 150 ≈ crisp without bloat.
FIGURE_RENDER_DPI = int(_env("FIGURE_RENDER_DPI", "150"))

# Database
DATABASE_PATH = _env("DATABASE_PATH", "./academictok.db")

# Firebase
FIREBASE_CRED_PATH = _env("FIREBASE_CRED_PATH", "authkey.json")

# Admin: emails allowed to access the ingestion dashboard. Stored in a secret
# file (one email per line, '#' comments allowed) so the list isn't in code/env.
ADMIN_EMAILS_PATH = _env("ADMIN_EMAILS_PATH", "admin_emails")


def admin_emails() -> set:
    """Read the admin allow-list from the secret file (lowercased).

    Read on each call so edits take effect without a server restart.
    """
    try:
        with open(ADMIN_EMAILS_PATH) as f:
            return {
                line.strip().lower()
                for line in f
                if line.strip() and not line.lstrip().startswith("#")
            }
    except FileNotFoundError:
        return set()

# Server / CORS
CORS_ORIGINS = [o.strip() for o in _env("CORS_ORIGINS").split(",") if o.strip()]
PORT = int(_env("PORT", "8080"))
DEBUG = _env("DEBUG", "false").lower() == "true"

# Feed
DEFAULT_PAGE_SIZE = 20
# Mixed-feed ratio: fraction of items drawn from subscribed fields.
MIXED_SUBSCRIBED_RATIO = 0.7
